defaults:
  - robotwin_task: orbit_so100_image
  - _self_

name: train_maniflow_image_orbit

task_name: ${robotwin_task.name}
shape_meta: ${robotwin_task.shape_meta}
exp_name: so100_maniflow_teabags_50_v2_150ep

horizon: 16
n_obs_steps: 2
n_action_steps: 16
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
keypoint_visible_rate: 1.0
obs_as_global_cond: true

policy:
  _target_: maniflow.policy.maniflow_image_policy.ManiFlowTransformerImagePolicy
  block_type: DiTX
  n_layer: 12
  n_head: 8
  n_emb: 768
  visual_cond_len: 1024
  max_lang_cond_len: 1024
  qkv_bias: true
  qk_norm: true

  language_conditioned: true
  pre_norm_modality: false

  flow_batch_ratio: 0.75
  consistency_batch_ratio: 0.25
  sample_t_mode_flow: beta
  sample_t_mode_consistency: discrete
  sample_dt_mode_consistency: uniform
  sample_target_t_mode: relative
  denoise_timesteps: 10

  diffusion_timestep_embed_dim: 128
  diffusion_target_t_embed_dim: 128

  horizon: ${horizon}
  n_action_steps: ${n_action_steps}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 10
  obs_as_global_cond: true
  shape_meta: ${shape_meta}

  obs_encoder:
    _target_: maniflow.model.vision_2d.transformer_obs_encoder.TransformerObsEncoder
    shape_meta: ${shape_meta}
    global_pool: ''
    n_emb: ${policy.n_emb}
    model_name: vit_base_patch16_clip_224.openai
    pretrained: true
    frozen: true
    feature_aggregation: null
    transforms:
      - type: RandomCrop
        ratio: 0.95
      - _target_: torchvision.transforms.RandomRotation
        degrees:
          - -5.0
          - 5.0
        expand: false
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.3
        contrast: 0.4
        saturation: 0.5
        hue: 0.08
    use_group_norm: false
    share_rgb_model: false

ema:
  _target_: maniflow.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 16
  num_workers: 4
  shuffle: true
  pin_memory: true
  persistent_workers: true
  drop_last: true

val_dataloader:
  batch_size: 16
  num_workers: 4
  shuffle: false
  pin_memory: true
  persistent_workers: false
  drop_last: true

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.9, 0.95]
  eps: 1.0e-8
  weight_decay: 1.0e-3

training:
  device: cuda:0
  env_device: cuda:0
  seed: 42
  debug: false
  resume: true
  resume_from_checkpoint: null
  advance_epoch_on_resume: true
  lr_scheduler: cosine
  lr_num_epochs: ${training.num_epochs}
  lr_warmup_steps: 500
  num_epochs: 151
  target_epoch: null
  gradient_accumulate_every: 8
  use_ema: true
  rollout_every: 100
  checkpoint_every: 25
  val_every: 10
  sample_every: 5
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0

logging:
  group: ${exp_name}
  id: null
  mode: online
  name: ${training.seed}
  project: ManiFlow_Orbit
  resume: true
  tags:
    - ${logging.project}
    - orbit_so100
    - teabags_kitting_50_v2
    - maniflow_image
    - 150_epochs

checkpoint:
  save_ckpt: true
  topk:
    monitor_key: val_loss
    mode: min
    k: 3
    format_str: epoch={epoch:04d}-val_loss={val_loss:.6f}.ckpt
  save_last_ckpt: true
  save_last_snapshot: false

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
